export type SocialDef = {
  id: string;
  label: string;
  color: string;
  placeholder: string;
};

/** Platforms users can attach — FA brands + custom marks */
export const SOCIAL_PLATFORMS: SocialDef[] = [
  { id: "discord", label: "Discord", color: "#5865F2", placeholder: "https://discord.com/users/..." },
  { id: "instagram", label: "Instagram", color: "#E1306C", placeholder: "https://instagram.com/..." },
  { id: "x-twitter", label: "X / Twitter", color: "#FFFFFF", placeholder: "https://x.com/..." },
  { id: "threads", label: "Threads", color: "#FFFFFF", placeholder: "https://threads.net/@..." },
  { id: "tiktok", label: "TikTok", color: "#FFFFFF", placeholder: "https://tiktok.com/@..." },
  { id: "youtube", label: "YouTube", color: "#FF0000", placeholder: "https://youtube.com/@..." },
  { id: "twitch", label: "Twitch", color: "#9146FF", placeholder: "https://twitch.tv/..." },
  { id: "kick", label: "Kick", color: "#53FC18", placeholder: "https://kick.com/..." },
  { id: "spotify", label: "Spotify", color: "#1DB954", placeholder: "https://open.spotify.com/..." },
  { id: "soundcloud", label: "SoundCloud", color: "#FF5500", placeholder: "https://soundcloud.com/..." },
  { id: "apple", label: "Apple Music", color: "#FA243C", placeholder: "https://music.apple.com/..." },
  { id: "bandcamp", label: "Bandcamp", color: "#1DA0C3", placeholder: "https://bandcamp.com/..." },
  { id: "deezer", label: "Deezer", color: "#A238FF", placeholder: "https://deezer.com/..." },
  { id: "lastfm", label: "Last.fm", color: "#D51007", placeholder: "https://last.fm/user/..." },
  { id: "itunes", label: "iTunes", color: "#FA57C1", placeholder: "https://music.apple.com/..." },
  { id: "steam", label: "Steam", color: "#66C0F4", placeholder: "https://steamcommunity.com/id/..." },
  { id: "xbox", label: "Xbox", color: "#107C10", placeholder: "https://account.xbox.com/..." },
  { id: "playstation", label: "PlayStation", color: "#0070D1", placeholder: "https://playstation.com/..." },
  { id: "roblox", label: "Roblox", color: "#E6362E", placeholder: "https://www.roblox.com/users/..." },
  { id: "osu", label: "osu!", color: "#FF66AA", placeholder: "https://osu.ppy.sh/users/..." },
  { id: "unity", label: "Unity", color: "#FFFFFF", placeholder: "https://..." },
  { id: "github", label: "GitHub", color: "#FFFFFF", placeholder: "https://github.com/..." },
  { id: "gitlab", label: "GitLab", color: "#FC6D26", placeholder: "https://gitlab.com/..." },
  { id: "stackoverflow", label: "Stack Overflow", color: "#F48024", placeholder: "https://stackoverflow.com/users/..." },
  { id: "npm", label: "npm", color: "#CB3837", placeholder: "https://www.npmjs.com/~..." },
  { id: "docker", label: "Docker", color: "#2496ED", placeholder: "https://hub.docker.com/u/..." },
  { id: "linkedin", label: "LinkedIn", color: "#0A66C2", placeholder: "https://linkedin.com/in/..." },
  { id: "reddit", label: "Reddit", color: "#FF4500", placeholder: "https://reddit.com/u/..." },
  { id: "telegram", label: "Telegram", color: "#26A5E4", placeholder: "https://t.me/..." },
  { id: "whatsapp", label: "WhatsApp", color: "#25D366", placeholder: "https://wa.me/..." },
  { id: "snapchat", label: "Snapchat", color: "#FFFC00", placeholder: "https://snapchat.com/add/..." },
  { id: "facebook", label: "Facebook", color: "#1877F2", placeholder: "https://facebook.com/..." },
  { id: "pinterest", label: "Pinterest", color: "#E60023", placeholder: "https://pinterest.com/..." },
  { id: "tumblr", label: "Tumblr", color: "#36465D", placeholder: "https://tumblr.com/..." },
  { id: "mastodon", label: "Mastodon", color: "#6364FF", placeholder: "https://mastodon.social/@..." },
  { id: "bluesky", label: "Bluesky", color: "#1185FE", placeholder: "https://bsky.app/profile/..." },
  { id: "vk", label: "VK", color: "#0077FF", placeholder: "https://vk.com/..." },
  { id: "weibo", label: "Weibo", color: "#E6162D", placeholder: "https://weibo.com/..." },
  { id: "wechat", label: "WeChat", color: "#07C160", placeholder: "https://..." },
  { id: "line", label: "LINE", color: "#00C300", placeholder: "https://line.me/..." },
  { id: "onlyfans", label: "OnlyFans", color: "#00AFF0", placeholder: "https://onlyfans.com/..." },
  { id: "patreon", label: "Patreon", color: "#FF424D", placeholder: "https://patreon.com/..." },
  { id: "paypal", label: "PayPal", color: "#00457C", placeholder: "https://paypal.me/..." },
  { id: "cashapp", label: "Cash App", color: "#00D632", placeholder: "https://cash.app/$..." },
  { id: "venmo", label: "Venmo", color: "#008CFF", placeholder: "https://venmo.com/u/..." },
  { id: "bitcoin", label: "Bitcoin", color: "#F7931A", placeholder: "bitcoin:..." },
  { id: "ethereum", label: "Ethereum", color: "#627EEA", placeholder: "https://..." },
  { id: "amazon", label: "Amazon", color: "#FF9900", placeholder: "https://amazon.com/..." },
  { id: "ebay", label: "eBay", color: "#E53238", placeholder: "https://ebay.com/usr/..." },
  { id: "etsy", label: "Etsy", color: "#F56400", placeholder: "https://etsy.com/shop/..." },
  { id: "shopify", label: "Shopify", color: "#96BF48", placeholder: "https://..." },
  { id: "behance", label: "Behance", color: "#1769FF", placeholder: "https://behance.net/..." },
  { id: "dribbble", label: "Dribbble", color: "#EA4C89", placeholder: "https://dribbble.com/..." },
  { id: "deviantart", label: "DeviantArt", color: "#05CC47", placeholder: "https://deviantart.com/..." },
  { id: "artstation", label: "ArtStation", color: "#13AFF0", placeholder: "https://artstation.com/..." },
  { id: "figma", label: "Figma", color: "#F24E1E", placeholder: "https://figma.com/@..." },
  { id: "sketch", label: "Sketch", color: "#F7B500", placeholder: "https://..." },
  { id: "medium", label: "Medium", color: "#FFFFFF", placeholder: "https://medium.com/@..." },
  { id: "notion", label: "Notion", color: "#FFFFFF", placeholder: "https://notion.so/..." },
  { id: "goodreads", label: "Goodreads", color: "#372213", placeholder: "https://goodreads.com/..." },
  { id: "letterboxd", label: "Letterboxd", color: "#00D735", placeholder: "https://letterboxd.com/..." },
  { id: "imdb", label: "IMDb", color: "#F5C518", placeholder: "https://imdb.com/name/..." },
  { id: "anilist", label: "AniList", color: "#02A9FF", placeholder: "https://anilist.co/user/..." },
  { id: "vimeo", label: "Vimeo", color: "#1AB7EA", placeholder: "https://vimeo.com/..." },
  { id: "unsplash", label: "Unsplash", color: "#FFFFFF", placeholder: "https://unsplash.com/@..." },
  { id: "flickr", label: "Flickr", color: "#FF0084", placeholder: "https://flickr.com/people/..." },
  { id: "strava", label: "Strava", color: "#FC4C02", placeholder: "https://strava.com/athletes/..." },
  { id: "link", label: "Website", color: "#FFFFFF", placeholder: "https://..." },
  { id: "envelope", label: "Email", color: "#FFFFFF", placeholder: "mailto:you@domain.com" },
];

export const BADGE_PRESETS = [
  { id: "star", label: "Star" },
  { id: "crown", label: "Crown" },
  { id: "fire", label: "Fire" },
  { id: "heart", label: "Heart" },
  { id: "bolt", label: "Bolt" },
  { id: "gem", label: "Gem" },
  { id: "shield", label: "Shield" },
  { id: "trophy", label: "Trophy" },
  { id: "rocket", label: "Rocket" },
  { id: "code", label: "Code" },
  { id: "music", label: "Music" },
  { id: "gamepad", label: "Gamepad" },
  { id: "ghost", label: "Ghost" },
  { id: "skull", label: "Skull" },
  { id: "moon", label: "Moon" },
  { id: "sun", label: "Sun" },
  { id: "leaf", label: "Leaf" },
  { id: "camera", label: "Camera" },
  { id: "palette", label: "Palette" },
  { id: "gift", label: "Gift" },
  { id: "key", label: "Key" },
  { id: "wand", label: "Magic" },
  { id: "dragon", label: "Dragon" },
  { id: "chess", label: "Chess" },
  { id: "certificate", label: "Craft" },
] as const;

/** Site owner Discord snowflake — gets Owner badge on public profiles */
export const OWNER_DISCORD_IDS = new Set(["1494801028619571221"]);
